### ISSUE TITLE
示范里的27k工作流里的[ImageFromBatch+]节点没办法找到

### ISSUE THREAD

**Issue by dxyklp** [huchenlei/ComfyUI_omost#18]
示范里的27k工作流里的[ImageFromBatch+]节点是那个插件里的，我按照[ComfyUI-Manager]里的提示需要要安装[ComfyUI Essentials],但我安装之后仍显示缺少[ImageFromBatch+]节点，难道是因为comfyui内核版本的bug吗？我使用了最新的[b1fd26f]6月5号更新的内核

**Comment by huchenlei** [comment]
It seems like comfyui has a native image from batch node. It just does not appear in the search result. Maybe due to id conflict? You can replace the ImageFromBatch+ node with that one by manually locate it under `image/batch`
https://github.com/comfyanonymous/ComfyUI/blob/b1fd26fe9e55163f780bf9e5f56bf9bf5f035c93/comfy_extras/nodes_images.py#L51-L68

**Comment by dxyklp** [comment]
好的,感谢
